mydbprojectponce/myapp1/urls.py
from django.urls import path
from myapp1 import views

app_name = 'myapp1'

urlpatterns = [

    path('', views.MyIndexView.as_view(), name="my_index_view"),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard_view"),
    # To replace "success page" and default the index page with '' (blank).
    path('index/', views.MyIndexView.as_view(), name="my_index_view"), #Specifies the path for index.html
    # Name the attribute of the path the same as the class but with underscores: "my_index_view"
    # MyIndexView is the name of the class from views.py
    # Create/Specify one path for everytime you want to render/view a html file in a browser
    path('features/', views.FeaturesView.as_view(), name="features_view"),
    path('aboutus/', views.AboutView.as_view(), name="aboutus_view"),
    path('contactus/', views.ContactView.as_view(), name="contactus_view"),
    path('signup/', views.SignUpView.as_view(), name="signup_view"),
    path('signin/', views.SignInView.as_view(), name="signin_view"),
    path('createPatient/', views.CreatePatientView.as_view(), name="createpatient_view"),
    path('createPhlebotomist/', views.CreatePhlebotomistView.as_view(), name="createphlebotomist_view"),
    path('createLocation/', views.CreateLocationView.as_view(), name="createlocation_view"),
    path('rolefinalization/', views.RoleFinalizationView.as_view(), name="rolefinalization_view"),
    path('addDonor/', views.AddDonorView.as_view(), name="addDonor_view"),
    path('addDonation/', views.AddDonationView.as_view(), name="addDonation_view"),
    path('addTransaction/', views.AddTransactionView.as_view(), name="addTransaction_view"),
    path('logout/', views.logout, name='logout')
]

mydbprojectponce/mydbprojectponce/urls.py
# mcwayneotsuki URL Configuration

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/3.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))

from django.contrib import admin
from django.urls import include, path

app_name = 'myapp1' # Specify the app name (myapp1)

urlpatterns = [
    path('admin/', admin.site.urls),
    # Default path which is the admin page, 
    # Admin page is where you login with 'python manage.py createsuperuser' account created
    path('myapp1/', include('myapp1.urls', namespace='myapp1')),

]                                    

mydbprojectponce/myapp1/models.py
#(models.py)
from django.db import models

# Create your models here.
# The tables will be created here, not in the phpMyAdmin database
# 'makemigrations' command to save the contents here
# model inherits models.Model

#new table
class Users(models.Model):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length = 20, unique=True)
    password = models.CharField(max_length = 20)

    class meta:
        db_table = 'Users'

    def __str__(self):
        return self.username

class Donors(models.Model):
    donor_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length = 40)
    last_name = models.CharField(max_length = 40)
    contact_number = models.CharField(max_length = 20)
    blood_type = models.CharField(max_length = 3)

    class meta: # Specifies the table name; For consistency, class name and table name are the same.
        db_table = 'Donors' 

class Patients(models.Model):
    patient_id = models.AutoField(primary_key=True)
    username = models.ForeignKey(Users,to_field='username',on_delete = models.CASCADE) #foreign key syntax
    first_name = models.CharField(max_length = 40)
    last_name = models.CharField(max_length = 40)
    contact_number = models.CharField(max_length = 20)
    blood_type = models.CharField(max_length = 3)

    class meta:
        db_table = 'Patients' 

class Phlebotomists(models.Model):
    pbt_id = models.AutoField(primary_key=True)
    username = models.ForeignKey(Users,to_field='username',on_delete = models.CASCADE) #foreign key syntax
    first_name = models.CharField(max_length = 40)
    last_name = models.CharField(max_length = 40)
    contact_number = models.CharField(max_length = 20)

    class meta:
        db_table = 'Phlebotomists' 
        
class Donations(models.Model):
    donation_id = models.AutoField(primary_key=True)
    donor_id = models.ForeignKey(Donors, on_delete = models.CASCADE)
    date_of_donation = models.DateField()
    amount = models.IntegerField()

    # class meta:
    #     db_table = 'Donations' 

class Donation_Transaction(models.Model):
    dt_id = models.AutoField(primary_key=True)
    pbt_id = models.ForeignKey(Phlebotomists, on_delete = models.CASCADE)
    patient_id = models.ForeignKey(Patients, on_delete = models.CASCADE)
    amount = models.IntegerField()
    date_donated = models.DateField()
    donation_id = models.ForeignKey(Donations, on_delete = models.CASCADE)
    blood_type = models.CharField(max_length = 3)

    class meta:
         db_table = 'Donation_Transaction' 

class Location(models.Model):
    loc_id = models.AutoField(primary_key=True)
    dt_id = models.ForeignKey(Donation_Transaction, on_delete = models.CASCADE)
    state = models.CharField(max_length = 50)
    city = models.CharField(max_length = 50)
    zip_code = models.CharField(max_length = 20) 
    date_of_transaction = models.DateField()
    
    class meta:
        db_table = 'Location'

mydbprojectponce/myapp1/forms.py
from django import forms
from .models import *

class PatientsForm(forms.ModelForm):
	class Meta:
		model = Patients
		fields= '__all__'

class PhlebotomistsForm(forms.ModelForm):
	class Meta:
		model = Phlebotomists
		fields= '__all__'

class LocationForm(forms.ModelForm):
	class Meta:
		model = Location
		fields= '__all__'

class DonationTransactionForm(forms.ModelForm):
	class Meta:
		model = Donation_Transaction
		fields= '__all__'

class UsersForm(forms.ModelForm):
    class Meta:
        model = Users
        fields= '__all__'		

class DonorsForm(forms.ModelForm):

    class Meta:
        model = Donors
        fields= '__all__'

mydbprojectponce/myapp1/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from django.views.generic import View
from django.http import HttpResponse
from django.views.generic import View
from .forms import *
from .models import *
from django.contrib.auth.models import User

# Create your views here.
class MyIndexView(View): 
    def get(self, request): 
        return render(request, 'pages/index.html', {})

class DashboardView(View): 
    def get(self, request):
        #changes here
        if 'user' in request.session:
            patients = Patients.objects.all()
            phlebotomists = Phlebotomists.objects.all()
            location = Location.objects.all()
            donation_transaction = Donation_Transaction.objects.all()
            current_user = request.session['user']
            context = {
                'patients' : patients,
                'phlebotomists' : phlebotomists,
                'location': location,
                'donation_transaction': donation_transaction,
                'current_user': current_user
            }
            return render(request, 'pages/dashboard.html', context)
        else:
            return HttpResponse('Please login first to view this page.') 
    def post(self, request):
       if request.method == 'POST':
            # no changes in update and delete (all tables)
            # Patients Table
            if 'btnUpdatePatient' in request.POST:
                print('Update button clicked!')
                pid = request.POST.get("patient_id")
                pfname = request.POST.get("first_name")
                plname = request.POST.get("last_name")
                pcnum = request.POST.get("contact_number")
                pbtype = request.POST.get("blood_type")
                update_Patient = Patients.objects.filter(patient_id=pid).update(first_name = pfname, last_name = plname, contact_number = pcnum, blood_type = pbtype)
                print(update_Patient)
                print('Patient record updated!')
            elif 'btnDeletePatient' in request.POST:
                print('Delete button clicked!')
                pid = request.POST.get("patient_id")
                Patients.objects.filter(patient_id=pid).delete()
                print("Patient record deleted")

            # Phlebotomists Table
            if 'btnUpdatePhlebotomist' in request.POST:
                print('Update button clicked!')
                phid = request.POST.get("pbt_id")
                phfname = request.POST.get("first_name")
                phlname = request.POST.get("last_name")
                phcnum = request.POST.get("contact_number")
                update_Phlebotomist = Phlebotomists.objects.filter(pbt_id=phid).update(first_name = phfname, last_name = phlname, contact_number = phcnum)
                print(update_Phlebotomist)
                print('Phlebotomist record updated!')
            elif 'btnDeletePhlebotomist' in request.POST:
                print('Delete button clicked!')
                phid = request.POST.get("pbt_id")
                Phlebotomists.objects.filter(pbt_id=phid).delete()
                print("Phlebotomist record deleted")

            # Locations Table
            if 'btnUpdateLocation' in request.POST:
                print('Update button clicked!')
                lid = request.POST.get("loc_id")
                lstate = request.POST.get("state")
                lcity = request.POST.get("city")
                lzipcode = request.POST.get("zip_code")
                ldot = request.POST.get("date_of_transaction")
                ldtid = request.POST.get("dt_id")
                update_Location = Location.objects.filter(loc_id=lid).update(dt_id= ldtid, state = lstate, city = lcity, zip_code = lzipcode, date_of_transaction = ldot)
                print(update_Location)
                print('Location record updated!')
            elif 'btnDeleteLocation' in request.POST:
                print('Delete button clicked!')
                lid = request.POST.get("loc_id")
                Location.objects.filter(loc_id=lid).delete()
                print("Location record deleted")

            return redirect('myapp1:dashboard_view')

class CreatePatientView(View):
    def get(self, request):
        #changes here
        if 'user' in request.session:
            current_user = request.session['user']
            context = {
                'current_user': current_user
            }
        return render(request, 'pages/createPatient.html',context)
    def post(self, request):        
        form = PatientsForm(request.POST, request.FILES)   
        #changes here with form.cleaned.data     
        if form.is_valid():
            # try:
            #pid = request.POST.get("patient_id")
            fk = form.cleaned_data.get("username")
            pfname = request.POST.get("first_name")
            plname = request.POST.get("last_name")
            pcnum = request.POST.get("contact_number")
            pbtype = request.POST.get("blood_type")
            form = Patients(username = fk, first_name = pfname, last_name = plname, contact_number = pcnum, blood_type = pbtype)
            form.save() 
            return redirect('myapp1:dashboard_view')
        else:
            print(form.errors)
            return HttpResponse('not valid')

class CreatePhlebotomistView(View):
    def get(self, request):
        #same changes with CreatePatientView
        if 'user' in request.session:
            current_user = request.session['user']
            context = {
                'current_user': current_user
            }
        return render(request, 'pages/createPhlebotomist.html',context)
    def post(self, request):        
        form = PhlebotomistsForm(request.POST, request.FILES)        
        if form.is_valid():
            # try:
            fk = form.cleaned_data.get("username")
            phlfname = request.POST.get("first_name")
            phllname = request.POST.get("last_name")
            phlcnum = request.POST.get("contact_number")
            form = Phlebotomists(username = fk,first_name = phlfname, last_name = phllname, contact_number = phlcnum)
            form.save() 
            return redirect('myapp1:dashboard_view')
        else:
            print(form.errors)
            return HttpResponse('not valid')

#no changes here
class CreateLocationView(View):
    def get(self, request):
        donation_transaction = Donation_Transaction.objects.all()
        context = {
            'donation_transaction': donation_transaction,
        }
        return render(request, 'pages/createLocation.html',context)
    def post(self, request):        
        form = LocationForm(request.POST, request.FILES)        
        if form.is_valid():
            # try:
            lstate = request.POST.get("state")
            lcity = request.POST.get("city")
            lzipcode = request.POST.get("zip_code")
            ldot = request.POST.get("date_of_transaction")
            ldtid = request.POST.get("dt_id")
            fk = form.cleaned_data.get("dt_id")
            form = Location(state = lstate, city = lcity, zip_code = lzipcode, date_of_transaction = ldot, dt_id = fk)
            form.save() 
            return redirect('myapp1:dashboard_view')
        else:
            print(form.errors)
            return HttpResponse('not valid')

class FeaturesView(View): 
    def get(self, request): 
        return render(request, 'pages/features.html', {})

class AboutView(View): 
    def get(self, request): 
        return render(request, 'pages/aboutus.html', {})

class ContactView(View): 
    def get(self, request): 
        return render(request, 'pages/contactus.html', {})
#changes here and SignInView      
class SignUpView(View): 
    def get(self, request): 
        return render(request, 'pages/signup.html', {})
    def post(self, request):        
        form = UsersForm(request.POST, request.FILES)        
        if form.is_valid():
            # try:
            username = request.POST.get("username")
            password = request.POST.get("password")
            if Users.objects.filter(username=username).count()>0:
                return HttpResponse('Username already exists.')
            else:
                form = Users(username = username, password = password)
                form.save()
                check_user = Users.objects.filter(username=username, password=password)
                if check_user:
                    request.session['user'] = username
                    return redirect('myapp1:rolefinalization_view')
        else:
            print(form.errors)
            return HttpResponse('not valid')
        
class SignInView(View): 
    def get(self, request): 
        return render(request, 'pages/signin.html', {})
    def post(self, request):
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            check_user = Users.objects.filter(username=username, password=password)
            if check_user:
                request.session['user'] = username
                return redirect('myapp1:dashboard_view')
            else:
                return HttpResponse('Please enter valid Username or Password.')
        return render(request, 'pages/signin.html', {})

#New View
class RoleFinalizationView(View):
    def get(self, request):
        if 'user' in request.session:
            current_user = request.session['user']
            context = {
                'current_user': current_user,
            }
            return render(request, 'pages/rolefinalization.html', context)
        else:
            return HttpResponse('Please login first to view this page.')


#logout code
def logout(request):
    try:
        del request.session['user']
    except:
        return redirect('myapp1:signin_view')
    return redirect('myapp1:signin_view')

class AddDonorView(View):
    def get(self, request): 

mydbprojectponce/myapp1/templates/pages/aboutus.html
{% load static %} <!--- Built-in helper in Django to load static; short-hand syntax --->

<!-- Header Start-->
{% block headerinclude %}

<title>About Us</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<link rel="stylesheet" type="text/css" href= "{% static 'css/styles.css' %}"/>
<style>
  body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
  body {font-size:16px;}
  .w3-half img {margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
  .w3-half img:hover {opacity:1}
</style>

{% endblock headerinclude %}
<!-- Header End -->

<!-- Content/Body Start -->
{% block content %} <!----------------------------------------------------------------->

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
  <div class="w3-container">
    <img src="{% static 'images/blood-donation.png' %}" style="width:50%; margin-bottom: -65px;" alt="Logo">
    <h2 class="w3-padding-64"><b>Blood Bank<br style="display: block; content: ''; margin-top: -7px;">System</b></h2>
  </div>
<div class="w3-bar-block">
    <a href="{% url 'myapp1:my_index_view' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Home</a> 
    <a href="{% url 'myapp1:features_view' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Features</a> 
    <a href="{% url 'myapp1:aboutus_view' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">About Us</a> 
    <a href="{% url 'myapp1:contactus_view' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Contact Us</a> 
    <a href="{% url 'myapp1:signin_view' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Sign In</a> 
    <a href="{% url 'myapp1:signup_view' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Sign Up</a>
  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
  <span>Company Name</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">

  
  <!-- Designers -->
  <div class="w3-container" id="designers" style="margin-top:75px; margin-bottom: 20px;">
    <img src="{% static 'images/hi.png' %}" style="width: 65px; float: left; margin-right: 7px; margin-top: 6.5px;">
    <h1 class="w3-xxxlarge w3-text-red"><b>About Us</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
    <p>We are the creators of this Bloodbank database system. We have found inspiration in creating a convenient,
      safe, and secure space for people who want to donate blood and/or in need of blood donations especially during this pandemic. Moreover, this website will also serve as a good starting point for future purposes to conduct seamless transactions between donors and patients all around the country. Should you have any suggestions or complaints, you can contact us through  <a href="tel:555-666-7777">+63912345678</a> or <a href = "mailto: test@gmail.com">test@gmail.com </a>
    </p>
  </div>

  <!-- The Team -->
  <div class="w3-row-padding w3-grayscale" style="text-align: center; filter: none;">

    <div class="w3-col m4 w3-margin-bottom" style="margin-left: 95px; margin-right:-160px;">
      <div class="w3-light-grey">
        <img src="{% static 'images/mcmc.jpg' %}" alt="Mcmc" style="height:265px;border-radius: 50%;">
        <div class="w3-container">
          <h3>McWayne Otsuki</h3>
          <p class="w3-opacity">Co-Creator</p>
          <p style="line-height: 0.5">BSIT-3 Student</p> 
          <p style="line-height: 0.5">CSIT 327-G1</p>
          <p style="line-height: 0.5">A.Y. 2021-2022</p>
        </div>
      </div>
    </div>
    
    <div class="w3-col m4 w3-margin-bottom">
      <div class="w3-container" style="width:32.3%;">
      </div>
  </div>

    <div class="w3-col m4 w3-margin-bottom"">
      <div class="w3-light-grey">
        <img src="{% static 'images/mike.jpg' %}" alt="Mike" style="height:265px;border-radius: 50%;">
        <div class="w3-container">
          <h3>
          </h3>
          <p class="w3-opacity">Co-Creator</p>
          <p style="line-height: 0.5">BSIT-3 Student</p> 
          <p style="line-height: 0.5">CSIT 327-G1</p>
          <p style="line-height: 0.5">A.Y. 2021-2022</p>
        </div>
      </div>
    </div>

  </div>

<!-- End page content -->
</div>


{% endblock content %} <!------------------------------------------------------------->
<!-- Content/Body End -->

<!-- Footer Start -->
{% block footerinclude %} <!---------------------------------------------------------->

<!-- W3.CSS Container -->
<div class="w3-light-grey w3-container w3-padding-32" style="margin-top: 75px; padding-right: 58px; position: relative; right: 0; bottom: 0; width: 100%;"><p class="w3-right">Otsuki, McWayne Q. CSIT327 G1-C1 A.Y. 2021-2022</p></div>

<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}
 
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}
</script>

{% endblock footerinclude %} <!-------------------------------------------------------->
<!-- Footer End -->

mydbprojectponce/myapp1/templates/pages/rolefinalization.html
{% load static %} <!--- Built-in helper in Django to load static; short-hand syntax --->

<!-- Header Start-->
{% block headerinclude %}

<title>Choose a Role</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<link rel="stylesheet" type="text/css" href= "{% static 'css/styles.css' %}"/>
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap.css' %}"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jq-3.6.0/dt-1.11.3/datatables.min.css"/>
<style>
  body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
  body {font-size:16px;}
  .w3-half img {margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
  .w3-half img:hover {opacity:1}
</style>

{% endblock headerinclude %}
<!-- Header End -->

<!-- Content/Body Start -->
{% block content %} <!----------------------------------------------------------------->

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
  <div class="w3-container">
   <img src="{% static 'images/blood-donation.png' %}" style="width:50%; margin-bottom: -65px;" alt="Logo">
    <h2 class="w3-padding-64"><b>Blood Bank<br style="display: block; content: ''; margin-top: -7px;">System</b></h2>
  </div>
  <div class="w3-bar-block">
    <a href="{% url 'myapp1:my_index_view' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Home</a> 
    <a href="{% url 'myapp1:features_view' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Features</a> 
    <a href="{% url 'myapp1:aboutus_view' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">About Us</a> 
    <a href="{% url 'myapp1:contactus_view' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Contact Us</a> 
    <a href="{% url 'myapp1:signin_view' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Sign In</a> 
    <a href="{% url 'myapp1:signup_view' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Sign Up</a>
  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
  <span>Company Name</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">

  <!-- Header -->
  <div class="w3-container" style="margin-top:80px" id="showcase">
   <img src="{% static 'images/hi.png' %}" style="width: 65px; float: left; margin-right: 10px; margin-top: 10px;">
    <h1 class="w3-xxxlarge w3-text-red" style="font-weight: bold;">Choose your role</h1>
    <hr style="width:50px;border:5px solid red;" class="w3-round">
    <br>

    <table>

        <tr>
        <td>
        <button class="w3-btn w3-block w3-padding w3-red w3-margin-bottom" style="font-size: 23px; font-weight: bold; letter-spacing: 5px; width: 100%; border-radius: 8px;"><img src="{% static 'images/youthtest.png' %}"><br><a href="{% url 'myapp1:createpatient_view' %}" onclick="w3_close()" class="w3-xxlarge w3-text-white">Patient</a></button>
        </td>
        <td>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </td>
        <td>
        <button class="w3-btn w3-block w3-padding w3-red w3-margin-bottom" style="font-size: 23px; font-weight: bold; letter-spacing: 5px; width: 100%; border-radius: 8px;"><img src="{% static 'images/addDVDtest2.png' %}"><br><a href="{% url 'myapp1:createphlebotomist_view' %}" onclick="w3_close()" class="w3-xxlarge w3-text-white">Phlebotomist</a></button>
        </td>
        </tr>

    <table>

    


<!-- End page content -->
</div>

{% endblock content %} <!------------------------------------------------------------->
<!-- Content/Body End -->

<!-- Footer Start -->
{% block footerinclude %} <!---------------------------------------------------------->

<!-- W3.CSS Container -->
<div class="w3-light-grey w3-container w3-padding-32" style="margin-top: 75px; padding-right: 58px; position: relative; right: 0; bottom: 0; width: 100%;"><p class="w3-right"s>Otsuki, McWayne Q. CSIT327 G1-C1 A.Y. 2021-2022</p></div>

 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/jq-3.6.0/dt-1.11.3/datatables.min.js"></script>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.dataTables.js' %}"></script>
<script type="text/javascript" src="{% static 'js/dataTables.bootstrap.js' %}"></script>



<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}
 
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}


</script>

{% endblock footerinclude %} <!-------------------------------------------------------->
<!-- Footer End -->